"""Emit a ROS 2 Humble launch.py that publishes the cleaned URDF.

OnShape exports a ROS 1 ``.launch`` XML. ROS 2 launch is Python, so
we generate a small ``display.launch.py`` that:

1. Reads the cleaned URDF (as a string) at launch time.
2. Spawns ``robot_state_publisher`` with that URDF as a parameter.
3. Spawns ``joint_state_publisher_gui`` so a developer can wiggle the
   wheel joints in RViz without a real controller.
4. Spawns RViz2 with the .rviz file the rviz_generator emits.

This launch file is intended for visual sanity-checking, not for the
real bringup -- the real bringup composes the description package
into ``fortis_bringup``. We emit it because it's the lowest-friction
way for the operator to look at the cleaned URDF after a tool run.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from typing import Optional


LAUNCH_TEMPLATE = '''\
"""
Display launch file for the FORTIS chassis URDF (generated by urdf_cleanup).

Spawns robot_state_publisher with the cleaned URDF, joint_state_publisher_gui
so the wheel joints can be wiggled by hand, and RViz2 loaded with the
matching display config. Intended for visual sanity-checking; the real
bringup composes the description package into fortis_bringup.
"""

from pathlib import Path

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


PACKAGE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_URDF = PACKAGE_DIR / "urdf" / "{urdf_filename}"
DEFAULT_RVIZ = PACKAGE_DIR / "rviz" / "{rviz_filename}"


def generate_launch_description():
    urdf_arg = DeclareLaunchArgument(
        "urdf_path",
        default_value=str(DEFAULT_URDF),
        description="Path to the URDF file to load.",
    )
    rviz_arg = DeclareLaunchArgument(
        "rviz_config",
        default_value=str(DEFAULT_RVIZ),
        description="Path to the RViz config to load.",
    )

    urdf_path = LaunchConfiguration("urdf_path")
    rviz_config = LaunchConfiguration("rviz_config")

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[{{"robot_description": _read_file(str(DEFAULT_URDF))}}],
    )

    jsp_gui = Node(
        package="joint_state_publisher_gui",
        executable="joint_state_publisher_gui",
        name="joint_state_publisher_gui",
        output="screen",
    )

    rviz = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", rviz_config],
    )

    return LaunchDescription([urdf_arg, rviz_arg, rsp, jsp_gui, rviz])


def _read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()
'''


def generate_display_launch(
    output_path: Path,
    urdf_filename: str = "fortis_chassis.urdf",
    rviz_filename: str = "fortis.rviz",
) -> Path:
    """Write a ``display.launch.py`` next to the cleaned URDF and rviz config.

    Returns the path the file was written to.
    """
    body = LAUNCH_TEMPLATE.format(
        urdf_filename=urdf_filename,
        rviz_filename=rviz_filename,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(body, encoding="utf-8")
    return output_path
